### ISSUE TITLE
Unable to install - neovim-pack-dir failed with exit code 1

### ISSUE THREAD

**Issue by vinylen** [NotAShelf/nvf#361] opened 2024-08-22 13:34 UTC
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

Hi,

I tried installing nvf as a nixos module and as a home-manager module using flakes but i got this error with both methods:

```
neovim-pack-dir> created 2 symlinks in user environment
neovim-pack-dir> /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc /build
neovim-pack-dir> Error detected while processing command line:
udev-rules> Copying /nix/store/qganx3pd2h510vvif6wfyzl6g8kvqnx2-modemmanager-1.22.0/lib/udev/rules.d/77-mm-x22x-port-types.rules to /nix/store/0xiyalaxlzxqzfl7v9ck3ba2j5fq6b6p-udev-rules/77-mm-x22x-port-types.rules
neovim-pack-dir> E151: No match: /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc/**
copying path '/nix/store/88g4bd87vvbkm4apmh0dbc3p4db68cg9-gnome-session-46.0-sessions' from 'https://cache.nixos.org'
error: builder for '/nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv' failed with exit code 1;
       last 4 log lines:
       > created 2 symlinks in user environment
       > /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc /build
       > Error detected while processing command line:
       > E151: No match: /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc/**
       For full logs, run 'nix log /nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv'.
error: 1 dependencies of derivation '/nix/store/1nhv253g5xyl8b3yb8bigb10waa6758v-neovim-0.9.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0qvr1zzlds8yb6dv9kq05b6frb5c64r9-nvf-with-helpers.drv' failed to build
error: 1 dependencies of derivation '/nix/store/43ah6y0887pbqqsnkxyh7v7hmw206wgw-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/33wxfsvxb9zysh36r1fsnm829js1wjqi-nixos-system-knut-24.05.20240821.224042e.drv' failed to build
┏━ 1 Errors:
┃ error: builder for '/nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv' failed with exit code 1;
┃        last 4 log lines:
┃        > created 2 symlinks in user environment
┃        > /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc /build
┃        > Error detected while processing command line:
┃        > E151: No match: /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc/**
┃        For full logs, run 'nix log /nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv'
```

### 👟 Reproduction steps

Add nvf as a flake input:

```
nvf = {
      url = "github:notashelf/nvf";
      # you can override input nixpkgs
      inputs.nixpkgs.follows = "nixpkgs";
      # you can also override individual plugins
      # for example:
      inputs.obsidian-nvim.follows = "obsidian-nvim"; # <- this will use the obsidian-nvim from your inputs
    };
```

Add `nvf.nixosModules.default` under nixosConfigurations.modules:

```
nixosConfigurations = {
  knut = nixpkgs.lib.nixosSystem {
    specialArgs = {inherit inputs outputs;};
    modules = [
      # > Our main nixos configuration file <
      ./nixos/configuration.nix
      nvf.nixosModules.default
    ];
  };
};
```

Add programs.nvf in configuration.nix:

```
  programs.nvf = {
    enable = true;
    # your settings need to go into the settings attribute set
    # most settings are documented in the appendix
    settings = {
      vim.viAlias = false;
      vim.vimAlias = true;
      vim.lsp = {
        enable = true;
      };
    };
  };
```

Rebuild nixos config

### 👀 Expected behavior

Expected behaviour would be for nvf to properly install in nixos

### 😓 Actual Behavior

Installation fails, error about neovim-pack-dir.

Output of `nix log /nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv`:

```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv^*'
created 2 symlinks in user environment
/nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc /build
Error detected while processing command line:
E151: No match: /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc/**
```

### 💻 Metadata

- system: `"x86_64-linux"`  - host os: `Linux 6.10.5, NixOS, 24.05 (Uakari), 24.05.20240819.f1bad50`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.18.5`  - nixpkgs: `/nix/store/1lwg74im5q4fmdk3zf5az570kixzk3vb-source`

### 📝 Relevant log output

```bash
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.5, NixOS, 24.05 (Uakari), 24.05.20240819.f1bad50`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/1lwg74im5q4fmdk3zf5az570kixzk3vb-source`


neovim-pack-dir> created 2 symlinks in user environment
neovim-pack-dir> /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc /build
neovim-pack-dir> Error detected while processing command line:
udev-rules> Copying /nix/store/qganx3pd2h510vvif6wfyzl6g8kvqnx2-modemmanager-1.22.0/lib/udev/rules.d/77-mm-x22x-port-types.rules to /nix/store/0xiyalaxlzxqzfl7v9ck3ba2j5fq6b6p-udev-rules/77-mm-x22x-port-types.rules
neovim-pack-dir> E151: No match: /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc/**
copying path '/nix/store/88g4bd87vvbkm4apmh0dbc3p4db68cg9-gnome-session-46.0-sessions' from 'https://cache.nixos.org'
error: builder for '/nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv' failed with exit code 1;
       last 4 log lines:
       > created 2 symlinks in user environment
       > /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc /build
       > Error detected while processing command line:
       > E151: No match: /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc/**
       For full logs, run 'nix log /nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv'.
error: 1 dependencies of derivation '/nix/store/1nhv253g5xyl8b3yb8bigb10waa6758v-neovim-0.9.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0qvr1zzlds8yb6dv9kq05b6frb5c64r9-nvf-with-helpers.drv' failed to build
error: 1 dependencies of derivation '/nix/store/43ah6y0887pbqqsnkxyh7v7hmw206wgw-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/33wxfsvxb9zysh36r1fsnm829js1wjqi-nixos-system-knut-24.05.20240821.224042e.drv' failed to build
┏━ 1 Errors:
┃ error: builder for '/nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv' failed with exit code 1;
┃        last 4 log lines:
┃        > created 2 symlinks in user environment
┃        > /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc /build
┃        > Error detected while processing command line:
┃        > E151: No match: /nix/store/yfb56ls9nfn0hjglkl67zr079drkb2v2-neovim-pack-dir/doc/**
┃        For full logs, run 'nix log /nix/store/ysvsa26zy5d6jfrh877zl3xhd3qrd942-neovim-pack-dir.drv'.
┣━ Dependency Graph:
┃    ┌─ ⏸ user-units waiting for 1 ⚠ 1 ⏵
┃    │  ┌─ ⏸ set-environment waiting for 1 ⚠ 1 ⏵
┃    ├─ ⏸ etc-profile
┃    ├─ ⏸ etc-pam-environment waiting for 1 ⚠ 1 ⏵
┃    │        ┌─ ⏵ home-manager-path
┃    │     ┌─ ⏸ home-manager-generation
┃    │  ┌─ ⏸ unit-home-manager-vicnil.service
┃    │  │     ┌─ ⏸ dbus-1 waiting for 1 ⚠ 1 ⏵
┃    │  │  ┌─ ⏸ X-Restart-Triggers-dbus
┃    │  ├─ ⏸ unit-dbus.service
┃    │  │  ┌─ ⏸ X-Restart-Triggers-polkit waiting for 1 ⚠ 1 ⏵
┃    │  ├─ ⏸ unit-polkit.service
┃    │  │           ┌─ ⚠ neovim-pack-dir failed with exit code 1 after ⏱ 0s
┃    │  │        ┌─ ⏸ neovim-0.9.5
┃    │  │     ┌─ ⏸ nvf-with-helpers
┃    │  │     ├─ ⏵ firefox-129.0.2
┃    │  │  ┌─ ⏸ system-path
┃    │  ├─ ⏸ unit-accounts-daemon.service
┃    ├─ ⏸ system-units
┃    ├─ ⏵ udev-rules
┃    ├─ ⏵ hwdb.bin
┃ ┌─ ⏸ etc
┃ ⏸ nixos-system-knut-24.05.20240821.224042e
┣━━━ Builds           │ Downloads       │ Host
┃    ⏵ 4 │     │      │     │     │     │ localhost
┃        │     │      │     │ ↓ 3 │     │ https://cache.nixos.org
┗━ ∑ ⏵ 4 │ ✔ 0 │ ⏸ 24 │ ↓ 0 │ ↓ 3 │ ⏸ 0 │ ⚠ Exited after 1 build failures at 15:20:44 after 14s
Error:
   0: Command exited with status Exited(1)

Location:
   src/commands.rs:151
```

**Comment by Gerg-L** [comment] 2024-08-22 14:12
Yeah it's a mnw issue, it's fixed in newer commits. But newer commits are broken on darwin because of my stupidity. I'll resolve it tonight

**Comment by Gerg-L** [comment] 2024-08-22 23:17
should be fixed

**Comment by vinylen** [comment] 2024-08-23 05:00
Hey, sorry to reopen this but there are still issues.

I ran nix flake update this morning and then tried to rebuild my nixos config, and now i got another error:

```
these 21 derivations will be built:
  /nix/store/n7inf8nv44b7a83c5gyy8965rafzhjr8-mnw-nvf-0.9.5.drv
  /nix/store/i62v6w980d0b5q7gcnx71cg1hmmr2xqh-nvf-with-helpers.drv
  /nix/store/jlri0nv6v4p2hrw0ar9ga1ij4v9lsbx3-system-path.drv
  /nix/store/3cqzl2c09nprrki0800m9xm6fliyx1wr-unit-accounts-daemon.service.drv
  /nix/store/v1y1mrbhla9mn6xsnml8y0kcyvn4mry9-home-manager-path.drv
  /nix/store/785zg3j6pf262rgjkx4ichyvjz450src-activation-script.drv
  /nix/store/64icvc1d6zgn9bmszyj08bvcwcwr6rf3-home-manager-generation.drv
  /nix/store/6fpdda1l0fkkfcgvj9cvnn8v7dv6339k-set-environment.drv
  /nix/store/8daxfjxwxlijg9krksz8ygzh2k70c41q-dbus-1.drv
  /nix/store/6qzhn0aivhjz0pcqvafdyz2ln0jd840h-X-Restart-Triggers-dbus.drv
  /nix/store/c93cavim9f4yi6xs2fk5q5dhv2fcimz6-unit-dbus.service.drv
  /nix/store/8a4dcb1fnrzkxynkfq8yw6gpliv3iiy5-user-units.drv
  /nix/store/aq3sy1q4nbm0npqdl83rzaw3n928a3hb-etc-profile.drv
  /nix/store/qmy7agajlxxg2gvg0kg0f5rpxpal0kad-etc-pam-environment.drv
  /nix/store/ikslg2y8jhvws63m6dnvqsv6v890l1xl-unit-dbus.service.drv
  /nix/store/fi1nng4yr08mlim6gwykjm9hmjrl8ry3-X-Restart-Triggers-polkit.drv
  /nix/store/q8i3fx39miarqq69gyh2bdrfpiry7q2i-unit-polkit.service.drv
  /nix/store/wdfqgx5pws0hbqbrnqd6734nz5a91l7q-unit-home-manager-vicnil.service.drv
  /nix/store/vv2vrj7v9l17a43rk4fyf52wlhwfhnmx-system-units.drv
  /nix/store/70zzapwgzi2ys9gfxh473c0yg0ays30w-etc.drv
  /nix/store/bgpg6qvhrkxq5prpz5wi04wg1zmwk4lp-nixos-system-knut-24.05.20240821.224042e.drv
mnw> building '/nix/store/n7inf8nv44b7a83c5gyy8965rafzhjr8-mnw-nvf-0.9.5.drv'
home-manager-path> building '/nix/store/v1y1mrbhla9mn6xsnml8y0kcyvn4mry9-home-manager-path.drv'
mnw> Running phase: patchPhase
mnw> Running phase: updateAutotoolsGnuConfigScriptsPhase
mnw> Running phase: configurePhase
mnw> no configure script, doing nothing
mnw> Running phase: buildPhase
mnw> no Makefile or custom buildPhase, doing nothing
mnw> Running phase: installPhase
mnw> /nix/store/qz53frww4qnx7p38q90kszlr4bhq2nfj-stdenv-linux/setup: line 1587: _addToLuaPath: command not found
error: builder for '/nix/store/n7inf8nv44b7a83c5gyy8965rafzhjr8-mnw-nvf-0.9.5.drv' failed with exit code 127;
       last 8 log lines:
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > no Makefile or custom buildPhase, doing nothing
       > Running phase: installPhase
       > /nix/store/qz53frww4qnx7p38q90kszlr4bhq2nfj-stdenv-linux/setup: line 1587: _addToLuaPath: command not found
       For full logs, run 'nix log /nix/store/n7inf8nv44b7a83c5gyy8965rafzhjr8-mnw-nvf-0.9.5.drv'.
error: 1 dependencies of derivation '/nix/store/i62v6w980d0b5q7gcnx71cg1hmmr2xqh-nvf-with-helpers.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jlri0nv6v4p2hrw0ar9ga1ij4v9lsbx3-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bgpg6qvhrkxq5prpz5wi04wg1zmwk4lp-nixos-system-knut-24.05.20240821.224042e.drv' failed to build
┏━ 1 Errors:
┃ error: builder for '/nix/store/n7inf8nv44b7a83c5gyy8965rafzhjr8-mnw-nvf-0.9.5.drv' failed with exit code 127;
┃        last 8 log lines:
┃        > Running phase: patchPhase
┃        > Running phase: updateAutotoolsGnuConfigScriptsPhase
┃        > Running phase: configurePhase
┃        > no configure script, doing nothing
┃        > Running phase: buildPhase
┃        > no Makefile or custom buildPhase, doing nothing
┃        > Running phase: installPhase
┃        > /nix/store/qz53frww4qnx7p38q90kszlr4bhq2nfj-stdenv-linux/setup: line 1587: _addToLuaPath: command not found
┃        For full logs, run 'nix log /nix/store/n7inf8nv44b7a83c5gyy8965rafzhjr8-mnw-nvf-0.9.5.drv'.
┣━ Dependency Graph:
┃    ┌─ ⏸ etc-pam-environment waiting for 1 ⚠
┃    ├─ ⏸ etc-profile waiting for 1 ⚠
┃    │  ┌─ ⏸ unit-dbus.service waiting for 1 ⚠
┃    ├─ ⏸ user-units
┃    ├─ ⏸ set-environment waiting for 1 ⚠
┃    │        ┌─ ⏸ activation-script waiting for 1 ⏵
┃    │        ├─ ⏵ home-manager-path
┃    │     ┌─ ⏸ home-manager-generation
┃    │  ┌─ ⏸ unit-home-manager-vicnil.service
┃    │  │  ┌─ ⏸ X-Restart-Triggers-polkit waiting for 1 ⚠
┃    │  ├─ ⏸ unit-polkit.service
┃    │  │     ┌─ ⏸ dbus-1 waiting for 1 ⚠
┃    │  │  ┌─ ⏸ X-Restart-Triggers-dbus
┃    │  ├─ ⏸ unit-dbus.service
┃    │  │        ┌─ ⚠ mnw-nvf-0.9.5 failed with exit code 127 after ⏱ 0s in installPhase
┃    │  │     ┌─ ⏸ nvf-with-helpers
┃    │  │  ┌─ ⏸ system-path
┃    │  ├─ ⏸ unit-accounts-daemon.service
┃    ├─ ⏸ system-units
┃ ┌─ ⏸ etc
┃ ⏸ nixos-system-knut-24.05.20240821.224042e
┣━━━ Builds
┗━ ∑ ⏵ 1 │ ✔ 0 │ ⏸ 19 │ ⚠ Exited after 1 build failures at 06:59:10 after 1s
Error:
   0: Command exited with status Exited(1)
```

**Comment by Gerg-L** [comment] 2024-08-23 09:48
Try removing your nvf `nixpkgs.follow`

**Comment by NotAShelf** [comment] 2024-08-23 09:59
@Gerg-L I thought we had already fixed the error in the log?

**Comment by vinylen** [comment] 2024-08-23 10:16
> Try removing your nvf `nixpkgs.follows`

Thanks for looking at this again. I have already removed `nixpkgs.follows`.

It looks like this now:


```
{
  description = "Vinylen nixos config";

  inputs = {
    # Nixpkgs
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    # Also see the 'unstable-packages' overlay at 'overlays/default.nix'.

    # home-manager, used for managing user configuration
    home-manager = {
      url = "github:nix-community/home-manager/release-24.05";
      # The `follows` keyword in inputs is used for inheritance.
      # Here, `inputs.nixpkgs` of home-manager is kept consistent with
      # the `inputs.nixpkgs` of the current flake,
      # to avoid problems caused by different versions of nixpkgs.
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nvf = {
      url = "github:notashelf/nvf";
      # inputs.nixpkgs.follows = "nixpkgs-unstable";
    };
  };

  outputs = {
    self,
    nixpkgs,
    nvf,
    ...
  } @ inputs: let
    inherit (self) outputs;
    # Supported systems for your flake packages, shell, etc.
    systems = [
      "x86_64-linux"
    ];
    # This is a function that generates an attribute by calling a function you
    # pass to it, with each system as an argument
    forAllSystems = nixpkgs.lib.genAttrs systems;
  in {
    # Your custom packages
    # Accessible through 'nix build', 'nix shell', etc
    packages = forAllSystems (system: import ./pkgs nixpkgs.legacyPackages.${system});
    # Formatter for your nix files, available through 'nix fmt'
    # Other options beside 'alejandra' include 'nixpkgs-fmt'
    formatter = forAllSystems (system: nixpkgs.legacyPackages.${system}.alejandra);

    # Your custom packages and modifications, exported as overlays
    overlays = import ./overlays {inherit inputs;};
    # Reusable nixos modules you might want to export
    # These are usually stuff you would upstream into nixpkgs
    nixosModules = import ./modules/nixos;
    # Reusable home-manager modules you might want to export
    # These are usually stuff you would upstream into home-manager
    homeManagerModules = import ./modules/home-manager;

    # NixOS configuration entrypoint
    # Available through 'nixos-rebuild --flake .#your-hostname'
    nixosConfigurations = {
      knut = nixpkgs.lib.nixosSystem {
        specialArgs = {inherit inputs outputs;};
        modules = [
          # > Our main nixos configuration file <
          ./nixos/configuration.nix
          nvf.nixosModules.default
        ];
      };
    };
  };
}

programs.nvf = {
    enable = true;
    # your settings need to go into the settings attribute set
    # most settings are documented in the appendix
    settings = {
      vim.viAlias = false;
      vim.vimAlias = true;
      vim.lsp = {
        enable = true;
      };
    };
  };
  
  
nix log /nix/store/1r96xj62s2wrlkkzb8gsv4lvdg7pafrw-mnw-nvf-0.9.5.drv

```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/1r96xj62s2wrlkkzb8gsv4lvdg7pafrw-mnw-nvf-0.9.5.drv^*'
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
no Makefile or custom buildPhase, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
/nix/store/yywfkjbmf0czk408qrqm691kclffvmg0-stdenv-linux/setup: line 1587: _addToLuaPath: command not found
```
```

**Comment by Gerg-L** [comment] 2024-08-23 23:25
ah, the issue is from using nixpkgs 24.05, i can add a check for this in mnw though

**Comment by Gerg-L** [comment] 2024-08-23 23:40
alright actually fixed
mnw change:
<https://github.com/Gerg-L/mnw/commit/6da0684d7fbfce4bd19b6bc9b7a86ba0ffc02cef>
nvf flake update:
<https://github.com/NotAShelf/nvf/pull/363>

**Comment by vinylen** [comment] 2024-08-25 19:39
Can confirm that it works now. Thanks for the work and assistance!

**Closed** 2024-08-26 09:37 UTC
Labels: bug
